### ISSUE TITLE
Where can I find all_sigs.mat?

### ISSUE THREAD

**Issue by TamTang222** [rsarka34/AsTFSONN#1]
Sorry to bother you, I would like to ask where I can find the 'all_sigs.ma' because I can only find the 'labels.xlsx' in the folder.
![asthma](https://github.com/rsarka34/AsTFSONN/assets/146698222/8ef88ff0-d3ca-4a95-9f6a-168d34b01d5c)

**Comment by rsarka34** [comment]
Dear Tam,
Please check the data folder. I have uploaded the signals, and please read "Data_readme.txt" before using them.

I hope it answers your query. 

with regards,
Arka.

**Comment by TamTang222** [comment]
Thank you for your information. I’ll make good use of it.

**Comment by rsarka34** [comment]
Thank you 😊. For any further query please feel free to raise an issue.
